### ISSUE TITLE
md5check the tarball distro download

### ISSUE THREAD

**Issue by samos123** [saltstack-formulas/zookeeper-formula#14] opened 2015-04-10 05:11 UTC
Would be better if we did a md5 check to make sure the download wasn't corrupted or hasn't been altered by a malicious person.

I can supply a pull request if consensus is to do this.

**Comment by 0xf10e** [comment] 2015-04-10 06:52
+1

**Comment by sroegner** [comment] 2015-04-10 12:30
+1 as long as the check is optional

**Comment by samos123** [comment] 2015-04-10 13:18
Why would you want to make it optional? Just wondering

**Comment by 0xf10e** [comment] 2015-04-10 16:02
@sroegner the default should still be to check

**Comment by samos123** [comment] 2015-04-11 05:30
I agree if it's optional you might as well not do it. So I was wondering
why would anybody want to turn it off. It makes absolutely no sense to me.
Waiting for sroegner's input.

Who wouldn't want to be sure that the package they download hasn't been
tampered with or was not corrupt?

**Comment by 0xf10e** [comment] 2015-04-11 11:40
Maybe if you placed your own patched version in the download dir?
But then I would rather overwrite URL & cksum via pillar…

**Comment by samos123** [comment] 2015-04-11 11:58
Yea true I guess that's the reasoning of making it optional. Some people
have no experience with checksums and they would have a hard time if
checksum is forced on them when they use custom URL / version.

**Comment by nmadhok** [comment] 2015-04-12 20:25
As long as the check is optional. The default should be to do a md5 check.

**Comment by sroegner** [comment] 2015-04-13 21:02
What is the intended behavior when the md5 is not provided?

**Comment by sroegner** [comment] 2015-04-13 21:03
@samos123 I don't care to validate packages every time i download them from our internal cache.

**Comment by 0xf10e** [comment] 2015-04-14 05:12
I would say "use the one from the formula" in case the URL is just a local cache. Together with a custom URL for a different/patched version that's probably the most common usecase.
To to disable the checking altogether I suggest a "checksum" of False.

**Comment by sroegner** [comment] 2015-04-14 11:06
@0xf10e I cannot agree to changing default behavior like that. Why not use the md5 only if one is provided? To do a meaningful check you will have to provide a hash anyway right?
Just imagine zookeeper 3.5 coming out then what will be our default url and md5 here?
Please get me right: I am fully on board with the idea of verification - I just don't see why we'd have to change the behavior of the formula for it.

**Comment by 0xf10e** [comment] 2015-04-14 18:20
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

@sroeger I didn't know the zookeeper folks stopped bothering with signing their releases or even providing a .md5 for their releases (they did until 3.3.2 or s/t [0]).
So yeah, there's no source of truth here anyway - else one could just grab the .md5 from their webserver (URL + ".md5") and check w/o someone updating the formula every release. The default would have been to check w/o any need to manually provide a cksum.

Providing a dict with version -> cksum mapping would still be nice. And maybe a force_cksum parameter that stops the formula from silently installing a version where the cksum has defaulted to False.

[0] http://archive.apache.org/dist/hadoop/zookeeper/
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFTBAEBCAA9BQJVLVpuNhxGbG9yaWFuIEVybWlzY2ggPGZsb3JpYW4uZXJtaXNj
aEBhbHVtbmkudHUtYmVybGluLmRlPgAKCRAu8tzCHoBI/SxRB/0T3y8/KhGJOqEu
6vce9JQF93sVEJa66oiXL7OnIb97NxmVKZmUtLnkNVH4mzwJo+MzWjOl5wXH+/Ny
PiM7ySnOFi3ctlwUmjTPGRJxH6sFEfLG8/uwGcAx+QOPwcUxTbkQ6+QnJUowDX2g
Ydz4U28+qt7tZuD+kEqas2HiDBJN0qsoEjsaD2cWIIspwxLyDETx/mWfvTL5Ymdu
UFXANFpO6g77q+ZHUEyNEXhonYzafEsv+3jITHuev4wYT1iwz8WiMPiLLL4mu1g7
5t3sIqvFo5m0pWYcCJnKe1hj3DbsQVM4kybRaJfpG8sLvFMFKqLuCjtbng3zGDmd
V/2KEJst
=H2Kd
-----END PGP SIGNATURE-----

**Comment by nilops** [comment] 2015-04-29 15:12
I think it might be an oversight by the Zookeeper team, I've posted an inquiry to the mailing list.

**Comment by nilops** [comment] 2015-04-29 19:39
Per the response from the ZK team, hash digests aren't mirrored.  This should be a simplification though, since a known canonical URL can be used for any given released version.  ex: https://www.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz.md5

**Comment by 0xf10e** [comment] 2015-04-29 19:56
Nice, should solve this problem ^^

**Comment by nilops** [comment] 2015-04-29 23:12
The ZK team opened up a ticket with the Apache Infrastructure team also to double check if the mirroring behavior is correct. https://issues.apache.org/jira/browse/INFRA-9556

**Comment by gravyboat** [comment] 2015-04-30 00:36
@nilops Thanks for keeping us up to date on this!

**Comment by ralph-tice** [comment] 2015-06-02 23:31
https://issues.apache.org/jira/browse/INFRA-9556 has been closed as not a problem / working as intended, so the URL I posted as nilops on the 29th above should be preferred for hashes/signatures.

**Comment by vutny** [comment] 2016-09-27 07:52
This should be resolved with merging PR #28

**Comment by timcharper** [comment] 2016-09-27 19:58
@sroegner in response to this discussion I have made it so providing an empty string to `source_md5` will disable md5 checking. However, by default it is on. Which is without question the right default.

**Comment by 0xf10e** [comment] 2016-12-23 11:06
Fixed by #28 then?

**Comment by ralph-tice** [comment] 2017-01-03 21:28
yep, @vutny can you close this? fixed by #28

**Comment by vutny** [comment] 2017-01-04 16:16
@ralph-tice I've seen that. Unfortunately, I don't have permissions to close any issues here :smile: 
Maybe @gravyboat or @sroegner can do it? Thanks for the heads up though.

**Closed** 2017-01-04 16:57 UTC

**Comment by vutny** [comment] 2017-01-05 14:06
Thanks @javierbertoli! Would you be able to maintain this repo and merge PR as well?
